spring:
  application:
    name: roomfinder-backend
  profiles:
    active: local, no-auth # Start in local profile on default for development
  threads:
    virtual:
      enabled: true
  cache:
    caffeine:
      spec: "maximumSize=500,expireAfterWrite=3600s"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/thrrosenheim

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      access: read_only

logging:
  level:
    com.kospaeth.roomfinder: DEBUG

room-finder:
  admin-ids:
    - i4nLJYwjqpTsUBU5K8eiEKWSFs23
  splan:
    url: "https://splan.th-rosenheim.de/splan/json"
  osm:
    over-pass-url: "https://overpass-api.de/api/interpreter"
    building-way-ids:
      # Rosenheim Standort
      # Hauptgebäude
      - regex: "A\\d\\.\\d{0,2}\\w?"
        buildingId: 28400949 # Building A
        name: "A"
        # Special case where AZ rooms are in Building B
      - regex: "AZ\\d\\.\\d{0,2}\\w?"
        buildingId: 28401106 # Building B
        name: "A"
      - regex: "B\\d\\.\\d{0,2}\\w?"
        buildingId: 28401106 # Building B
        name: "B"
      # Gebäude S
      - regex: "S\\d\\.\\d{0,3}\\w?"
        buildingId: 28401224
        name: "S"
