spring:
  application:
    name: roomfinder-backend
  profiles:
    active: local, no-auth # Start in local profile on default for development
  threads:
    virtual:
      enabled: true
  cache:
    caffeine:
      spec: "maximumSize=500,expireAfterWrite=3600s"

logging:
  level:
#    reactor.netty.http.client.HttpClient: DEBUG
    com.kospaeth.roomfinder: DEBUG

room-finder:
  splan:
    url: "https://splan.th-rosenheim.de/splan/json"
  osm:
    over-pass-url: "https://overpass-api.de/api/interpreter"
    building-way-ids:
      # Hauptgebäude
      - regex: "A\\d\\.\\d{0,2}\\w?"
        buildingId: 28400949 # Building A
        name: "A"
      - regex: "B\\d\\.\\d{0,2}\\w?"
        buildingId: 28401106 # Building B
        name: "B"
  admin-ids:
    - test
