spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/roomFinderDB
    username: user
    password: password

  flyway:
    url: jdbc:postgresql://localhost:5432/roomFinderDB
    user: user
    password: password
    baseline-on-migrate: true
