name: 'Build frontend image'
description: 'Action to build frontend image'

inputs:
  image_tag:
    description: "Image Tag to use"
  backend_url:
    description: "Backend url used for the frontend"
    default: https://api.thrroomfinder.duell10111.de
  maptiler_api_key:
    description: "Maptiler API Key"
  indoor_control_api_key:
    description: "Indoor Control API Key"
  firebase_api_key:
    description: "Firebase Web API Key"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/duell10111/thr-roomfinder/frontend:${{ inputs.image_tag }}
        context: frontend
        build-args: |
          NEXT_PUBLIC_MAPTILER_API_KEY=${{ inputs.maptiler_api_key }} 
          NEXT_PUBLIC_INDOOR_CONTROL_API_KEY=${{ inputs.indoor_control_api_key }}
          NEXT_PUBLIC_FIREBASE_API_KEY=${{ inputs.firebase_api_key }}
          NEXT_PUBLIC_BACKEND_URL=${{ inputs.backend_url }}
