services:
  db:
    image: postgis/postgis:15-3.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=roomFinderDB

