name: Code analysis

on:
  push:

permissions:
  contents: read

jobs:
  Frontend-Analysis:
    name: Frontend Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
        working-directory: frontend # Run in frontend folder
      - run: npm run lint
        name: "Lint check"
        working-directory: frontend # Run in frontend folder
      - run: npm run test
        working-directory: frontend # Run in frontend folder
  Backend-Analysis:
    name: Backend Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: "Unit Tests"
        run: gradle test
        working-directory: roomfinder-backend # Run in backend folder
      - name: "Architecture Tests"
        run: gradle konsistTest
        working-directory: roomfinder-backend # Run in backend folder
