name: Deployment

on:
  push:

permissions:
  packages: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Publish image to Github
        run: |
          gradle jib \
            --image=ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }} \
            -Djib.to.auth.username=${{ github.actor }} \
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
        env:
          IMAGE_TAG: CANARY
        working-directory: roomfinder-backend # Run in backend folder
